version: '3.7'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server-container
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=EducaMix@123
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql

  api:
    build: .
    container_name: api-container
    depends_on:
      - sqlserver
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=sqlserver
      - DB_PORT=1433
      - DB_USER=sa
      - DB_PASSWORD=EducaMix@123
      - DB_NAME=educamix
    networks:
      - mynetwork

volumes:
  sql-data:

networks:
  mynetwork:
    driver: bridge
